## This configure used to generate guides docs only. Not for API


xcodebuild_arguments: ['-scheme', 'TestingHostApp', '-project', 'serrano.xcodeproj']
module: Serrano

author: pcpLiu
author_url: https://github.com/pcpLiu
github_url: https://github.com/pcpLiu/Serrano
module_version: v0.1.0-alpha
github_file_prefix: https://github.com/pcpLiu/Serrano/tree/v0.1.0-alpha
root_url: http://serrano-lib.org/docs/v0.1.0-alpha/guides
theme: docs/fullwidth
output: docs/generated_docs/v0.1.0-alpha/guides

# Generate guides only
exclude: Source/*


documentation: docs/guides/**/*.md
abstract: docs/sections/**/*.md'
readme: docs/sections/Home.md


# Layout
custom_categories:
  - name: 'Getting started'
    children:
      - 'What is Serrano'
      - 'Core concepts'
  - name: 'Extension'
    children:
      - 'Write your own operator'
      - 'Write your own optimizer'
  - name: 'Contribution'
    children: [Contribution]
  - name: 'API Reference'
    children: [API Reference]
