site_name: Serrano Guides
theme:
  name: 'material'
  logo: 'doc_log.png'
  palette:
    primary: 'red'
    accent: 'deep orange'

repo_url: https://github.com/pcpLiu/Serrano
repo_name: Serrano

site_author: pcpLiu
site_description: Serrano Framework Guides
copyright:  Copyright (c) 2017, Zhonghao (Tim) Liu

site_dir: generated_docs

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
    version: v0.1.1-alpha


pages:
  - Home: 'index.md'
  - Get started:
    - 'Install': 'Getting started/Install.md'
    - 'Quick Start: SimpleCNN': 'Getting started/Quick Start Simple CNN.md'
    - 'Core Concepts':
      - 'Tensor': 'Getting started/Core concepts/Tensor.md'
      - 'Operator': 'Getting started/Core concepts/Operator.md'
      - 'Graph and Symbol': 'Getting started/Core concepts/Graph.md'
    - 'FAQ': 'Getting started/FAQ.md'
  - Extensibility:
    - 'Write your own operators' : 'Extension/Write your own operator.md'
    - 'Write your own optimizers': 'Extension/Write your own optimizer.md'
  - API Reference: 'API/API Reference.md'
  - Contribution: 'Contribution/Contribution.md'